import type { IndicatorPreset } from './types';

export const INDICATOR_PRESETS: IndicatorPreset[] = [
    {
        id: 'finra-short-volume',
        label: 'FINRA Short Volume',
        description: 'Direct short-volume columns with a 5-bar average.',
        sourcePath: 'presets/finra-short-volume.pine',
    },
    {
        id: 'ema-cross',
        label: 'EMA Cross',
        description: 'Fast/slow moving average overlay for trend structure.',
        sourcePath: 'presets/ema-cross.pine',
    },
    {
        id: 'bollinger-bands',
        label: 'Bollinger Bands',
        description: 'Configurable Bollinger Bands with selectable basis MA.',
        sourcePath: 'presets/bollinger-bands.pine',
        warmupBars: 40,
    },
    {
        id: 'bb-percent-b',
        label: 'Bollinger Bands %b',
        description: 'Classic Bollinger Bands %b oscillator.',
        sourcePath: 'presets/bb-percent-b.pine',
        warmupBars: 40,
    },
    {
        id: 'rsi',
        label: 'RSI',
        description: 'Momentum oscillator in a lower pane.',
        sourcePath: 'presets/rsi.pine',
    },
    {
        id: 'macd',
        label: 'MACD',
        description: 'MACD lines and histogram.',
        sourcePath: 'presets/macd.pine',
    },
    {
        id: 'supertrend',
        label: 'Supertrend',
        description: 'ATR-based trend overlay with directional line breaks.',
        sourcePath: 'presets/supertrend.pine',
        warmupBars: 30,
    },
    {
        id: 'delta-delta-turn-scanner',
        label: 'Delta Delta Cycle Reversal Scanner',
        description: 'Overlay reversal scanner that marks likely tops and bottoms directly on candles using price/return BB%b and second-derivative turns.',
        sourcePath: 'presets/delta-delta-turn-scanner.pine',
        warmupBars: 720,
    },
    {
        id: 'short-volume-profile',
        label: 'Short Volume Profile',
        description: 'Date-range profile built from FINRA short volume or close*short volume.',
        sourcePath: 'presets/short-volume-profile.pine',
    },
    {
        id: 'returns-bollinger-bands',
        label: 'Returns + Bollinger Bands',
        description: 'Multi-horizon return oscillator with optional averages and Bollinger bands.',
        sourcePath: 'presets/returns-bollinger-bands.pine',
        warmupBars: 800,
    },
    {
        id: 'returns-percent-b',
        label: 'Returns %b',
        description: 'Percent-b oscillator over period returns.',
        sourcePath: 'presets/returns-percent-b.pine',
        warmupBars: 800,
    },
    {
        id: 'returns-percent-b-20-260',
        label: 'Returns %b (20,260)',
        description: 'Percent-b oscillator over 20-bar returns with a 260-bar Bollinger window.',
        sourcePath: 'presets/returns-percent-b-20-260.pine',
        warmupBars: 400,
    },
    {
        id: 'sochan-band',
        label: 'Sochan Band',
        description: 'Short volume oscillator with half Bollinger bands, split adjustment, and market-cap ratio mode.',
        sourcePath: 'presets/sochan-band.pine',
        warmupBars: 260,
    },
    {
        id: 'sochan-band-mcap-ratio',
        label: 'Sochan Band MCAP/AUM Ratio',
        description: 'Sochan Band with short-value normalized by market cap for stocks or AUM for funds.',
        sourcePath: 'presets/sochan-band-mcap-ratio.pine',
        warmupBars: 260,
    },
    {
        id: 'sochan-rollshort',
        label: 'Sochan Rolling Short Pressure Oscillator',
        description: 'Rolling short-value pressure oscillator with percentile or stochastic normalization.',
        sourcePath: 'presets/sochan-rollshort.pine',
        warmupBars: 360,
    },
    {
        id: 'financial-assets-composite',
        label: 'Financial Assets Composite',
        description: 'Total assets and total equity composite with optional smoothing and moving averages.',
        sourcePath: 'presets/financial-assets-composite.pine',
    },
    {
        id: 'financial-returns-composite',
        label: 'Financial Returns Composite',
        description: 'ROA, ROE, and ROTE composite with optional smoothing and moving averages.',
        sourcePath: 'presets/financial-returns-composite.pine',
    },
];
